config/routes.rb
Rails.application.routes.draw do
  resources :habits do
    member do
      get :progress
    end
    resources :checkins, only: [ :create, :destroy ]
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "home#index"

  get "home/about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/checkin.rb
class Checkin < ApplicationRecord
  belongs_to :user
  belongs_to :habit

  validates :date, uniqueness: { scope: [ :habit_id, :user_id ] }
  def start_time
    created_at
  end
end

app/models/habit.rb
class Habit < ApplicationRecord
  belongs_to :user
  has_many :checkins, dependent: :destroy

  validates :title, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 500 }

  def current_streak(user)
    streak = 0
    today = Date.today

    while checkins.exists?(user: user, date: today - streak)
      streak += 1
    end
    streak
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :habits, dependent: :destroy
  # if user deleted, destroy their habits
  has_many :checkins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  before_action :set_habit, :authenticate_user!

  # POST /checkins or /checkins.json
  def create
    @habit.checkins.create(user: current_user, date: Date.today)
    redirect_back fallback_location: habits_path, notice: "Habit checked in!"
  end

  def destroy
    checkin = @habit.checkins.find(params[:id])
    checkin.destroy if checkin.user == current_user
    redirect_back fallback_location: habits_path,  notice: "Check-in removed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checkin
      @checkin = Checkin.find(params.expect(:id))
    end

    def set_habit
      @habit = Habit.find(params[:habit_id])
    end

    # Only allow a list of trusted parameters through.
    def checkin_params
      params.expect(checkin: [ :user_id, :habit_id, :checked_in, :date ])
    end
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :authenticate_user!, :set_habit, only: %i[ show edit update destroy ]

  # GET /habits or /habits.json
  def index
    @habits = current_user.habits
  end

  # GET /habits/1 or /habits/1.json
  def show
    @habit = current_user.habits.find(params[:id])
  end

  # GET /habits/new
  def new
    @habit = Habit.new
  end

  # GET /habits/1/edit
  def edit
  end

  # POST /habits or /habits.json
  def create
    @habit = current_user.habits.build(habit_params)

    respond_to do |format|
      if @habit.save
        format.html { redirect_to habits_path, notice: "Habit was successfully created." }
        format.json { render :show, status: :created, location: @habit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  def progress
    @habit = Habit.find(params[:id])
  end
  # PATCH/PUT /habits/1 or /habits/1.json
  def update
    respond_to do |format|
      if @habit.update(habit_params)
        format.html { redirect_to habits_path, notice: "Habit was successfully updated." }
        format.json { render :show, status: :ok, location: @habit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /habits/1 or /habits/1.json
  def destroy
    @habit.destroy!

    respond_to do |format|
      format.html { redirect_to habits_path, status: :see_other, notice: "Habit was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_habit
      @habit = Habit.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def habit_params
      params.expect(habit: [ :title, :description ])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!
    def index
        render
    end
    def about
        render
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/views/checkins/_checkin.html.erb
<div id="<%= dom_id checkin %>">
  <p>
    <strong>User:</strong>
    <%= checkin.user_id %>
  </p>

  <p>
    <strong>Habit:</strong>
    <%= checkin.habit_id %>
  </p>

  <p>
    <strong>Checked in:</strong>
    <%= checkin.checked_in %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= checkin.date %>
  </p>

</div>

app/views/checkins/_form.html.erb
<%= form_with(model: checkin) do |form| %>
  <% if checkin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(checkin.errors.count, "error") %> prohibited this checkin from being saved:</h2>

      <ul>
        <% checkin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :habit_id, style: "display: block" %>
    <%= form.text_field :habit_id %>
  </div>

  <div>
    <%= form.label :checked_in, style: "display: block" %>
    <%= form.checkbox :checked_in %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/checkins/edit.html.erb
<% content_for :title, "Editing checkin" %>

<h1>Editing checkin</h1>

<%= render "form", checkin: @checkin %>

<br>

<div>
  <%= link_to "Show this checkin", @checkin %> |
  <%= link_to "Back to checkins", checkins_path %>
</div>

app/views/checkins/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Checkins" %>

<h1>Checkins</h1>

<div id="checkins">
  <% @checkins.each do |checkin| %>
    <%= render checkin %>
    <p>
      <%= link_to "Show this checkin", checkin %>
    </p>
  <% end %>
</div>

<%= link_to "New checkin", new_checkin_path %>

app/views/checkins/new.html.erb
<% content_for :title, "New checkin" %>

<h1>New checkin</h1>

<%= render "form", checkin: @checkin %>

<br>

<div>
  <%= link_to "Back to checkins", checkins_path %>
</div>

app/views/checkins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @checkin %>

<div>
  <%= link_to "Edit this checkin", edit_checkin_path(@checkin) %> |
  <%= link_to "Back to checkins", checkins_path %>

  <%= button_to "Destroy this checkin", @checkin, method: :delete %>
</div>

app/views/habits/_checkin_form.erb
<% checked_in = habit.checkins.find_by(user: current_user, date: Date.today) %>


<% if checked_in %>
  <%= button_to habit_checkin_path(habit, checked_in), method: :delete, form: {data: {turbo: false}}, class: "btn p-0 border-0 bg-transparent"  do %>
    <i class="bi bi-check-circle-fill text-success fs-1 pe-4" style="cursor: pointer;"></i>
  <% end %>
<% else %>
  <%= form_with(model: Checkin.new, url: habit_checkins_path(habit), method: :post, local: true ) do |form| %>
    <% if habit.errors.any? %>
      <div style="color: red">
    <% end %>
    <%= form.hidden_field :habit_id, value: habit.id %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.hidden_field :date, value: Date.today %>
    
    <button type="submit" class="btn p-0 border-0 bg-transparent" id="checkin-button-<%= habit.id %>" >
      <i class="bi bi-circle text-muted fs-1 pe-4" style="cursor: pointer;" ></i>
    </button>
  <% end %>
<% end %>

app/views/habits/_form.html.erb
<%= form_with(model: habit) do |form| %>
  <% if habit.errors.any? %>
    <div class="alert alert-danger">
      <h4 class="alert-heading">
        <%= pluralize(habit.errors.count, "error") %> prohibited this habit from being saved:</h2>
      </h4>
      <ul>
        <% habit.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control", required: true %>
  </div>

  <div>
    <%= form.label :description, class: "form-label" %>
    <%= form.textarea :description, class: "form-control", required: true %>
  </div>

  <div>
    <%= form.submit "Create Habit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/habits/_habit.html.erb
<div>
  <h5 class="card-title mb-1"><%= habit.title %></h5>
  <p class="card-text mb-2"><%= habit.description %></p>
  <%= link_to "View Habit", "#habitModal-#{habit.id}", 
            class: "btn btn-secondary", 
            data: { bs_toggle: "modal", bs_target: "#habitModal-#{habit.id}" } %>
</div>

app/views/habits/_habit_modal.html.erb
<div class="modal fade" id="habitModal-<%= habit.id %>" tabindex="-1" aria-labelledby="habitModalLabel-<%= habit.id %>" aria-hidden="true" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="habitModalLabel-<%= habit.id %>"><%= habit.title %> Details</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h6>Description:</h6>
        <p><%= habit.description %></p>

        <h6>Check-in Streak:</h6>
        <p><%= habit.current_streak(current_user) %> days</p>

        <h6>Actions:</h6>
        <%= link_to "Edit Habit", edit_habit_path(habit), class: "btn btn-primary"%>
        <%= button_to habit_path(habit), 
            method: :delete, 
            data: {turbo_confirm: "Are you sure you want to delete this habit?"},
            class: "btn btn-danger" do%>
          Delete Habit
        <% end %>
        <%= link_to "View Progress via Calendar", progress_habit_path(habit), class: "btn btn-primary"%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/habits/_progress_chart.erb
<div class="row">
  <div>
    <%=  line_chart @habit.checkins.group_by_day(:date).count, height: "300px" %>
  </div>
</div>

app/views/habits/edit.html.erb
<% content_for :title, "Editing habit" %>

<div class="container mt-4 col-md-6">
  <h1 class="mb-4">Editing Habit</h1>

  <%= render "form", habit: @habit %>

  <div class="mt-3">
    <%= link_to "Back", habits_path, class: "btn btn-outline-secondary" %>
  </div>

</div>

app/views/habits/index.html.erb
<% content_for :title, "Habits" %>

<h1 class="text-center my-4">My Habits </h1>
<div class="d-flex justify-content-between align-items-center px-3 mb-2" style="max-width: 650px; margin: 0 auto;">
  <%= link_to "Add New Habit", new_habit_path, class: "btn btn-outline-dark" %>
  <p class="mb-0 fs-5 text-muted">Check in for <%= Date.today.strftime("%B %e, %Y") %></p>
</div>
<div class="d-flex justify-content-center">
  <div class="scroll-container rounded p-3 mb-2" style="height: 800px; overflow-y: auto; width: 100%; max-width: 700px">
    <% if current_user %>
      <div id="habits" class="mb-4 mt-1 me-3 ms-3">
        <% @habits.each do |habit| %>
          <div class="card mb-3">
            <div class="card-body d-flex justify-content-between align-items-center">
              <%= render "habit", habit: habit %>
              <%= render "habit_modal", habit: habit %>
              <%=  render "checkin_form", habit: habit, checked_in: habit.checkins.exists?(user: current_user, date: Date.today) %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/habits/new.html.erb
<% content_for :title, "New habit" %>

<div class="container mt-4 col-md-6">
  <h1 class="mb-4">New habit</h1>

  <%= render "form", habit: @habit %>

  <div class="mt-3">
    <%= link_to "Back", request.referer, class: "btn btn-outline-secondary" %>
  </div>

</div>

app/views/habits/progress.html.erb
<%= link_to "Back to Habits", habits_path, class: "btn btn-secondary mb-3" %>

<p>
  <span class="badge bg-primary fs-4 py-2 px-3">
    Current Streak:<%= @habit.current_streak(current_user)%> 
  </span>
</p>

<%= month_calendar(events: @habit.checkins) do |date, checkins| %>
 <div class="calendar-header text-center mb-3">
    
  </div>

   <%= date.day %>
  <% if checkins.any? %>
    <div class="checkin-day">
      ✅
    </div>
  <% end %>
  </div>
<% end %>

app/views/habits/show.html.erb
<%= render @habit %>

<div>
  <%= link_to "Edit this habit", edit_habit_path(@habit) %> |
  <%= link_to "Back to habits", habits_path %>

  <%= button_to "Destroy this habit", @habit, method: :delete %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light border border-secondary mb-4 py-3">
  <div class="container">
    <%= link_to "HabitTracker", root_path, class: "navbar-brand fs-2" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "Add Habit", new_habit_path, class: "nav-link fs-4" %>
        </li>
          <li class="nav-item">
            <%= link_to "View Habits", habits_path, class: "nav-link fs-4" %>
        </li>
      </ul>
      <div class="d-flex align-items-center ms-auto">
        <% if user_signed_in? %>
          <span class="navbar-text me-3">
            Hello, <%=current_user.email %>!
          </span>
          <a class="nav-item">
            <%= link_to 'Logout', destroy_user_session_path, data: { "turbo-method": :delete} %>
          </a>
        <% else %>
          <a class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path %> |
            <%= link_to 'Login', new_user_session_path %>
          </a>
        <% end %>
      </div>
    </div>
  </div>
</nav>

<%# basic nav bar using devise%>
<div class="container">
  <% if notice %>
    <div class="alert alert-success"><%= notice %></div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger"><%= alert %></div>
  <% end %>
</div>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Welcome to HabitTracker!</h1>
  <p class="lead">Get started by adding a daily habit or viewing your created habits.</p>
  <hr class="my-4">
  <div class="d-flex gap-3">
    <%= link_to "Add New Habit", new_habit_path, class: "btn btn-primary btn-lg"%>
    <%= link_to "View Created Habits", habits_path, class: "btn btn-primary btn-lg"%>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <title>Habit Tracker</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= turbo_include_tags %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>  
  </head>
  <body class="bg-light">
    <%=  render "home/header" %>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
  </body>
</html>